set_property SRC_FILE_INFO {cfile:C:/VIVADO_TESTS/Transmission_Dynamique/Transmission_Dynamique.srcs/constrs_1/imports/Transmissiondynamique/constraints.xdc rfile:../../../Transmission_Dynamique.srcs/constrs_1/imports/Transmissiondynamique/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports btn0]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports TxD]
