set_property SRC_FILE_INFO {cfile:{D:/Documents/fac/M1/_semestre2/projet conception/jalonFinal_joliMot - vivado/jalonFinal_joliMot - vivado.srcs/constrs_1/imports/new/constraints.xdc} rfile:{../../../jalonFinal_joliMot - vivado.srcs/constrs_1/imports/new/constraints.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports btn0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports btn1]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports TxD]
